### ISSUE TITLE
PyCoSim Initial Proposal

### ISSUE THREAD

**Issue by andrewandrepowell** [pycosim/discussion#1]
This issue will consist of our initial proposal in the design of the entire Python Cooperative Simulation suite, and I'm using suite as a way to refer to all the layers, including the PyCoSim layer itself. At this point, anything could change. We just a need a common place where we can brainstorm our ideas. Below is the current proposal

# Structure

The suite will be divided into the following layers. Each layer will be its own repository.

- Simulator
  - GPI
    - GPI C++ library
    - Simulator APIs (e.g. VPI, VHPI, FLI, etc.)
  - PyGPI
    - Simulator Module.
  - PyCoSim
    - Parts of PyCoSim will need to implemented on the Simulator side with PyZMQ. 
- Test
  - PyCoSim
    - PyZMQ with asyncio, utilizing the publisher and subscriber topology. Simulator would be the publisher, whereas the Test would be the subscriber. Blocking on triggers involve sending a message to the simulator, and then blocking until the corresponding message is published by the simulator.
    - Blocks, Drivers, Monitors, Models, etc. These will all build on top of the asyncio and the underlining triggers. This layer should probably be distinctive from the Triggers, Simulation Handles, and other low-level API stuff.
    - asyncio's event looper will be scheduler.

# Plan

1. Fork cocotb and strip away everything above the Simulator Module. In the future, this will get re-written as part of the PyGPI layer. The GPI layer will also get separated out in the future and polished.
2. Determine the PyCoSim API. This will consists of the Triggers, Simulation Handles, and other API.

**Comment by ktbarrett** [comment]
asyncio cannot be used to more easily implement a scheduler of this type.

To decide when to return from python and let the simulator continue there must be a way of deciding that all living coroutines are waiting on either a trigger or another coroutine. Essentially we are detecting deadlock. While this is possible you end up having to write a content tracker that is more or less what cocotb already has with it's scheduler; it's a lot of code. If you allow mixing this with outside asyncio code this becomes an undecidable problem (halting problem).

The idea is unfortunately untenable.
